import argparse
def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--exp', type=str,  default='output', help='model_name')
    parser.add_argument('--max_epoch', type=int,  default=100, help='maximum epoch number to train')
    parser.add_argument('--client_num', type=int, default=9, help='client number')
    parser.add_argument('--batch_size', type=int, default=10, help='batch_size per gpu')
    parser.add_argument('--image_size', type=int, default=1024, help='image_size')
    parser.add_argument('--clip_value', type=float,  default=100, help='maximum epoch number to train')
    parser.add_argument('--meta_step_size', type=float,  default=1e-3, help='maximum epoch number to train')
    parser.add_argument('--base_lr', type=float,  default=0.0001, help='maximum epoch number to train')
    parser.add_argument('--deterministic', type=int,  default=1, help='whether use deterministic training')
    parser.add_argument('--seed', type=int,  default=1337, help='random seed')
    parser.add_argument('--gpu', type=str,  default='0', help='GPU to use')
    parser.add_argument('--display_freq', type=int, default=20, help='batch_size per gpu')
    parser.add_argument('--unseen_site', type=int, default=0, help='batch_size per gpu')
    parser.add_argument('--pretrain', type=str, default=None, help='pretrain model')
    parser.add_argument('--sam_ckpt', type=str, default='/mnt/diskB/lyx/FedSAM/FedSAM/SAM/sam_vit_b_01ec64.pth', help='pretrain Sam model')
    parser.add_argument('--sam_type', default='vit_b' , help='sam type')
    parser.add_argument('--thd', type=bool, default=False , help='3d or not')
    parser.add_argument('--roi_size', type=int, default=96 , help='resolution of roi')
    parser.add_argument('--num_classes', type=int, default=1 , help='number of classes')
    parser.add_argument('--start_epoch', type=int, default=0 , help='start epoch for training')
    parser.add_argument('--data', type=str,  default='FeTS2022', help='dataset')
    parser.add_argument('--weights', type=str, default = 0, help='the weights file you want to test')
    parser.add_argument('--gpu_device', type=int, default=0, help='use which gpu')
    parser.add_argument('--sample_rate', type=float, default=0.5, help='sample rate of generated data')
    parser.add_argument('--tempre', type=float, default=1.0, help='tempreture of KD')
    parser.add_argument('--lam', type=float, default=0.5, help='tempreture of KD')
    parser.add_argument('--kd_epoch', type=int, default=0, help='start epoch for kd')
    parser.add_argument('--feature', type=bool, default=False, help='use feature loss or not')
    parser.add_argument('--student_types', type=str, default='unet,unet,unet,unet', help='unet/tinysam')
    parser.add_argument('--tea_ckpt', type=str, default='/mnt/diskB/lyx/FedSAM/FedSAM/SAM/sam_vit_b_01ec64.pth', help='pretrain Syn Sam model')
    parser.add_argument('--stu_ckpt', type=str, default='/mnt/diskB/lyx/FedSAM/FedSAM/SAM/sam_vit_b_01ec64.pth', help='pretrain TinySam or UNet model')
    parser.add_argument('--stu_ckpt_unet', type=str, default='/mnt/diskB/lyx/FedSAM/FedSAM/SAM/sam_vit_b_01ec64.pth', help='pretrain TinySam or UNet model')
    parser.add_argument('--baseline_ckpt', type=str, default='/mnt/diskB/lyx/FedSAM/FedSAM/SAM/sam_vit_b_01ec64.pth', help='Federated Sam model')
    parser.add_argument('--controlnet_dir', type=str, default=None, help='Directory with uploaded per-client ControlNet branches')
    parser.add_argument('--generate_syn_data', action='store_true', help='Generate synthetic data from ControlNet branches before mutual KD')
    parser.add_argument('--samples_per_client', type=int, default=100, help='Synthetic samples to generate per client when --generate_syn_data is set')
    parser.add_argument('--controlnet_aggregate', action='store_true', help='Average ControlNet branches before synthetic data generation')
    parser.add_argument('--enable_private_fedavg', action='store_true', help='Run TinySAM client training on private data with FedAvg between KD epochs')
    parser.add_argument('--private_fedavg_steps', type=int, default=1, help='Local TinySAM batches per client in each private FedAvg round')
    parser.add_argument('--learnability_conf_weight', type=float, default=0.5, help='Weight of SAM confidence in learnability sample selection')
    args = parser.parse_args()
    return args